import { NextRequest, NextResponse } from 'next/server'
import { getCalendarClient } from '@/lib/google'
import { appendScopingCall } from '@/lib/sheets'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import type { CalendarEvent } from '@/types'
import { triggerWebhook } from '@/lib/webhook'

const CALENDAR_ID = process.env.GOOGLE_CALENDAR_ID || 'primary'

/**
 * POST /api/calendar
 * Creates a Google Calendar event with Google Meet link.
 * Body: CalendarEvent
 */
export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body: CalendarEvent & { leadName?: string; leadId?: string; company?: string } = await req.json()
    const { summary, description, startDateTime, endDateTime, attendees, location, leadId } = body

    if (!summary || !startDateTime || !endDateTime) {
      return NextResponse.json({ error: 'Missing required: summary, startDateTime, endDateTime' }, { status: 400 })
    }

    const calendar = await getCalendarClient()

    // Duration in minutes
    const start  = new Date(startDateTime)
    const end    = new Date(endDateTime)
    const dur    = Math.round((end.getTime() - start.getTime()) / 60000)

    const event = await calendar.events.insert({
      calendarId: CALENDAR_ID,
      conferenceDataVersion: 1,    // generates Google Meet link
      sendNotifications: true,
      requestBody: {
        summary,
        description: description || `
Scoping Call — Vertex AI Marketing CRM

Lead: ${body.leadName || attendees?.[0]?.name || 'Prospect'}
Company: ${body.company || ''}

Agenda:
1. Current pain points & manual processes
2. AI/Automation readiness assessment
3. Recommended solutions & ROI estimate
4. Next steps

Generated by Vertex AI Marketing CRM`,
        start: { dateTime: startDateTime, timeZone: 'Asia/Manila' },
        end:   { dateTime: endDateTime,   timeZone: 'Asia/Manila' },
        location: location || 'Google Meet (link below)',
        attendees: [
          { email: session.user.email, displayName: 'Angelo Franco', responseStatus: 'accepted', organizer: true },
          ...(attendees || []).map(a => ({
            email:       a.email,
            displayName: a.name,
            responseStatus: 'needsAction',
          })),
        ],
        conferenceData: {
          createRequest: {
            requestId:             `vertex-crm-${Date.now()}`,
            conferenceSolutionKey: { type: 'hangoutsMeet' },
          },
        },
        reminders: {
          useDefault: false,
          overrides: [
            { method: 'email', minutes: 60 },
            { method: 'popup', minutes: 15 },
          ],
        },
        colorId: '9', // Blueberry — matches CRM electric blue
      },
    })

    const meetLink = event.data.conferenceData?.entryPoints?.find(e => e.entryPointType === 'video')?.uri

    // Save to Google Sheets → Scoping Calls tab
    if (body.leadName) {
      await appendScopingCall({
        leadName:        body.leadName,
        leadEmail:       attendees?.[0]?.email || '',
        company:         body.company || '',
        scheduledAt:     startDateTime,
        durationMinutes: dur,
        leadId:          leadId || undefined,
        notes:           description,
        googleEventId:   event.data.id || undefined,
        meetLink:        meetLink || undefined,
      })
    }

    // Fire n8n webhook — after both Calendar insert and Sheets append
    await triggerWebhook('call_booked', {
      leadId:        leadId ?? null,
      leadName:      body.leadName ?? null,
      company:       body.company  ?? null,
      startDateTime,
      meetLink:      meetLink ?? null,
    })

    return NextResponse.json({
      success:       true,
      eventId:       event.data.id,
      eventLink:     event.data.htmlLink,
      meetLink,
      startDateTime,
      endDateTime,
    })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    console.error('[API /calendar POST]', message)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}

/**
 * GET /api/calendar?days=7
 * Returns upcoming events from the CRM calendar.
 */
export async function GET(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const url  = new URL(req.url)
    const days = parseInt(url.searchParams.get('days') || '14') || 14

    const calendar  = await getCalendarClient()
    const timeMin   = new Date().toISOString()
    const timeMax   = new Date(Date.now() + days * 86400000).toISOString()

    const res = await calendar.events.list({
      calendarId: CALENDAR_ID,
      timeMin,
      timeMax,
      singleEvents: true,
      orderBy:      'startTime',
      maxResults:   50,
    })

    const events = (res.data.items || []).map(e => ({
      id:             e.id,
      summary:        e.summary,
      start:          e.start?.dateTime || e.start?.date,
      end:            e.end?.dateTime   || e.end?.date,
      attendees:      e.attendees?.map(a => ({ email: a.email, name: a.displayName, status: a.responseStatus })),
      meetLink:       e.conferenceData?.entryPoints?.find(ep => ep.entryPointType === 'video')?.uri,
      htmlLink:       e.htmlLink,
      description:    e.description,
      status:         e.status,
    }))

    return NextResponse.json({ events })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}

/**
 * DELETE /api/calendar?eventId=xxx
 * Cancels a scheduled scoping call.
 */
export async function DELETE(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const url     = new URL(req.url)
    const eventId = url.searchParams.get('eventId')
    if (!eventId) return NextResponse.json({ error: 'Missing eventId' }, { status: 400 })

    const calendar = await getCalendarClient()
    await calendar.events.delete({
      calendarId: CALENDAR_ID,
      eventId,
      sendNotifications: true,
    })

    return NextResponse.json({ success: true })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
